### PR TITLE
Create a script to make it easier to add groups for users

### PR DESCRIPTION
**Pull request by nerdstrike**
Is this what you had in mind @mgcam ? Or do you need even more admin capabilities?

### CODE REVIEW

**Comment by jenniferliddle** [comment]
At a minimum I would suggest adding -h, -? and --help options together with a 'Usage' display.

'Nice to have' would be options to display a list of valid roles, and existing roles for a given user.

**Comment by nerdstrike** [comment]
To be fair, it probably shouldn't set my role by default either... Tweaks will be forthcoming

**Comment by nerdstrike** [comment]
@jenniferliddle - is that more to your liking?

**Comment by jenniferliddle** [comment]
> @jenniferliddle - is that more to your liking?

Yay! That looks good :-)

The only problem I have is that when I try to run it I get an error:

> DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::mysql::st execute failed: INSERT command denied to user 'npgro'@'seqfarm3-head2.internal.sanger.ac.uk'

Is that just because I have an odd .npg/npg_tracking-Schema file?

**Comment by nerdstrike** [comment]
I think that's a fairly straightforward issue. You do what you've got to do to get `npgrw` as your database user. The --list options should still work for `npgro` but... that's the least exciting bit. The script is leaning on the "npg" way of authenticating, so it can't do anything about picking your tracking DB user.

**Pull request merged**
