### PR TITLE
Remove old team names from 'add run' dropdown

### PR DESCRIPTION
**Pull request by mksanger**
Remove options 'B', 'C' and 'joint'.

### CODE REVIEW

**Comment by mksanger** [comment]
Resolves [RT736224](https://rt.sanger.ac.uk/Ticket/Display.html?id=736224)

**Review by mgcam — CHANGES_REQUESTED** [review]
Incorrect team validation against the redundant list of teams.
The old list of teams is no longer needed in the run model.

**Comment by mksanger** [comment]
Don't we need to be able to validate old team names so that we can display old runs?

**Comment by mgcam** [comment]
On 06/01/2022 10:39, mksanger wrote:
>
> Don't we need to be able to validate old team names so that we can 
> display old runs?
>
As far as I can see, the validation is only performed when a new run is 
created.
>
> Message ID: ***@***.***>
>


-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Review by mgcam — APPROVED** [review]

**Pull request merged**
