### PR TITLE
Travis tweaks

### PR DESCRIPTION
**Pull request by dkj**
Add 5.22 Perl to build matrix and deploy to GitHub Releases

### CODE REVIEW

**Comment by dkj** [comment]
Rebased following #333

**Comment by mgcam** [comment]
Travis build for perl 5.16 (production version) succeeds, for perl 5.22 fails for a reason not related to this pull requests. The failure to be investigated later and fixed separately.

**Comment by dkj** [comment]
N.b. post-merge [Travis build](https://travis-ci.org/wtsi-npg/npg_tracking/builds/124872333) for 5.22 works okay

**Comment by mgcam** [comment]
There might be some weakness in that test, ie it might be failing randomly. I'll look into this if we see this failure again.

**Pull request merged**
